"""
JCAP Construction Suite
SMB Authentication Service

Handles Windows authentication to the Synology SMB server used by
JCAP document storage.

Responsibilities:
- Detect whether the configured SMB server/share is reachable.
- Establish a Windows SMB session using supplied Synology credentials.
- Optionally persist credentials in Windows Credential Manager.
- Detect common Windows SMB authentication/session errors.

Passwords are never written to JCAP logs, the database, or .env.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

from config import settings


class SMBAuthenticationError(RuntimeError):
    """Raised when Windows cannot authenticate to the SMB server."""


class SMBAuthenticationService:
    """Windows SMB authentication helper for JCAP shared storage."""

    ERROR_LOGON_FAILURE = 1326
    ERROR_SESSION_CREDENTIAL_CONFLICT = 1219
    ERROR_ACCESS_DENIED = 5

    @classmethod
    def is_windows(cls) -> bool:
        return sys.platform.startswith("win")

    @classmethod
    def get_document_root(cls) -> str:
        return str(settings.DOCUMENT_ROOT or "").strip()

    @classmethod
    def get_server(cls) -> str:
        """
        Return the SMB server portion of DOCUMENT_ROOT.

        Example:
            \\\\192.168.50.39\\JCAP Main Office Shared Folder\\...
            -> 192.168.50.39
        """
        document_root = cls.get_document_root()

        if not document_root.startswith("\\\\"):
            raise SMBAuthenticationError(
                "JCAP document storage is not configured as a UNC path."
            )

        parts = document_root.lstrip("\\").split("\\")

        if not parts or not parts[0].strip():
            raise SMBAuthenticationError(
                "The Synology SMB server could not be determined "
                "from DOCUMENT_ROOT."
            )

        return parts[0].strip()

    @classmethod
    def get_server_unc(cls) -> str:
        return rf"\\{cls.get_server()}"

    @classmethod
    def get_share_unc(cls) -> str:
        """
        Return only the UNC share root.

        Example:
            \\\\192.168.50.39\\JCAP Main Office Shared Folder
        """
        document_root = cls.get_document_root()

        if not document_root.startswith("\\\\"):
            raise SMBAuthenticationError(
                "JCAP document storage is not configured as a UNC path."
            )

        parts = document_root.lstrip("\\").split("\\")

        if len(parts) < 2:
            raise SMBAuthenticationError(
                "The Synology SMB share could not be determined "
                "from DOCUMENT_ROOT."
            )

        server = parts[0].strip()
        share = parts[1].strip()

        if not server or not share:
            raise SMBAuthenticationError(
                "The Synology SMB share configuration is incomplete."
            )

        return rf"\\{server}\{share}"

    @classmethod
    def has_access(cls) -> bool:
        """
        Return True when Windows can currently access the configured
        JCAP document root.

        No credential prompt is generated by this method.
        """
        if not cls.is_windows():
            return True

        document_root = cls.get_document_root()

        if not document_root:
            return False

        try:
            return Path(document_root).exists()
        except OSError:
            return False

    @classmethod
    def require_access(cls) -> None:
        """
        Raise SMBAuthenticationError when the JCAP document root is not
        currently accessible.
        """
        if cls.has_access():
            return

        raise SMBAuthenticationError(
            "Windows is not currently authenticated to the "
            "JCAP Synology shared folder."
        )

    @classmethod
    def authenticate(
        cls,
        username: str,
        password: str,
        *,
        remember: bool = True,
    ) -> None:
        """
        Authenticate Windows to the Synology SMB share.

        When remember=True, the credential is stored through Windows
        Credential Manager using cmdkey.

        The password is passed directly to Windows commands and is never
        returned or written to JCAP logs.
        """
        if not cls.is_windows():
            raise SMBAuthenticationError(
                "SMB authentication setup is supported only on Windows."
            )

        normalized_username = str(username or "").strip()
        normalized_password = str(password or "")

        if not normalized_username:
            raise SMBAuthenticationError(
                "Enter your Synology username."
            )

        if not normalized_password:
            raise SMBAuthenticationError(
                "Enter your Synology password."
            )

        server = cls.get_server()
        share_unc = cls.get_share_unc()

        if cls.has_access():
            return

        # Remove a stale connection to this specific server/share.
        # This is especially useful after a user changes their NAS password.
        cls._disconnect_share(ignore_errors=True)

        if remember:
            cls._save_windows_credential(
                server=server,
                username=normalized_username,
                password=normalized_password,
            )

        result = cls._connect_share(
            share_unc=share_unc,
            username=normalized_username,
            password=normalized_password,
        )

        if result.returncode != 0:
            if remember:
                # Do not leave a bad credential saved on the computer.
                cls._delete_windows_credential(
                    server,
                    ignore_errors=True,
                )

            cls._raise_connection_error(result)

        if not cls.has_access():
            if remember:
                cls._delete_windows_credential(
                    server,
                    ignore_errors=True,
                )

            cls._disconnect_share(ignore_errors=True)

            raise SMBAuthenticationError(
                "Windows accepted the SMB connection, but the "
                "JCAP shared folder is still not accessible. "
                "Check the Synology account's shared-folder permissions."
            )

    @classmethod
    def disconnect(cls) -> None:
        """
        Disconnect the current JCAP SMB share session.

        Saved Windows credentials are intentionally preserved.
        """
        if not cls.is_windows():
            return

        cls._disconnect_share(ignore_errors=False)

    @classmethod
    def forget_saved_credential(cls) -> None:
        """
        Remove the saved Windows credential for the Synology server.

        The active SMB session is also disconnected.
        """
        if not cls.is_windows():
            return

        server = cls.get_server()

        cls._disconnect_share(ignore_errors=True)
        cls._delete_windows_credential(
            server,
            ignore_errors=True,
        )

    # ========================================================
    # WINDOWS COMMANDS
    # ========================================================

    @classmethod
    def _connect_share(
        cls,
        *,
        share_unc: str,
        username: str,
        password: str,
    ) -> subprocess.CompletedProcess[str]:
        """
        Establish the SMB session.

        shell=False is intentional. It prevents shell interpretation of
        usernames/passwords containing command characters.
        """
        return subprocess.run(
            [
                "net",
                "use",
                share_unc,
                password,
                f"/user:{username}",
                "/persistent:no",
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            shell=False,
            creationflags=cls._creation_flags(),
        )

    @classmethod
    def _disconnect_share(
        cls,
        *,
        ignore_errors: bool,
    ) -> None:
        share_unc = cls.get_share_unc()

        result = subprocess.run(
            [
                "net",
                "use",
                share_unc,
                "/delete",
                "/y",
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            shell=False,
            creationflags=cls._creation_flags(),
        )

        if (
            not ignore_errors
            and result.returncode != 0
            and "2250" not in cls._combined_output(result)
        ):
            raise SMBAuthenticationError(
                cls._clean_command_error(result)
                or "Unable to disconnect the Synology SMB session."
            )

    @classmethod
    def _save_windows_credential(
        cls,
        *,
        server: str,
        username: str,
        password: str,
    ) -> None:
        result = subprocess.run(
            [
                "cmdkey",
                f"/add:{server}",
                f"/user:{username}",
                f"/pass:{password}",
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            shell=False,
            creationflags=cls._creation_flags(),
        )

        if result.returncode != 0:
            raise SMBAuthenticationError(
                cls._clean_command_error(result)
                or "Windows could not save the Synology credential."
            )

    @classmethod
    def _delete_windows_credential(
        cls,
        server: str,
        *,
        ignore_errors: bool,
    ) -> None:
        result = subprocess.run(
            [
                "cmdkey",
                f"/delete:{server}",
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            shell=False,
            creationflags=cls._creation_flags(),
        )

        if not ignore_errors and result.returncode != 0:
            raise SMBAuthenticationError(
                cls._clean_command_error(result)
                or "Windows could not remove the saved Synology credential."
            )

    # ========================================================
    # ERROR HANDLING
    # ========================================================

    @classmethod
    def _raise_connection_error(
        cls,
        result: subprocess.CompletedProcess[str],
    ) -> None:
        output = cls._combined_output(result)
        error_code = cls._extract_system_error(output)

        if error_code == cls.ERROR_LOGON_FAILURE:
            raise SMBAuthenticationError(
                "The Synology username or password is incorrect."
            )

        if error_code == cls.ERROR_SESSION_CREDENTIAL_CONFLICT:
            raise SMBAuthenticationError(
                "Windows already has an SMB connection to the Synology "
                "server using different credentials. Close any open NAS "
                "folders and try again."
            )

        if error_code == cls.ERROR_ACCESS_DENIED:
            raise SMBAuthenticationError(
                "The Synology account does not have permission to access "
                "the JCAP shared folder."
            )

        cleaned_error = cls._clean_command_error(result)

        if cleaned_error:
            raise SMBAuthenticationError(cleaned_error)

        raise SMBAuthenticationError(
            "Windows could not connect to the JCAP Synology shared folder."
        )

    @staticmethod
    def _extract_system_error(output: str) -> int | None:
        match = re.search(
            r"System error\s+(\d+)",
            output or "",
            flags=re.IGNORECASE,
        )

        if not match:
            return None

        try:
            return int(match.group(1))
        except ValueError:
            return None

    @staticmethod
    def _combined_output(
        result: subprocess.CompletedProcess[str],
    ) -> str:
        stdout = str(result.stdout or "").strip()
        stderr = str(result.stderr or "").strip()

        return "\n".join(
            value
            for value in (stdout, stderr)
            if value
        )

    @classmethod
    def _clean_command_error(
        cls,
        result: subprocess.CompletedProcess[str],
    ) -> str:
        output = cls._combined_output(result)

        if not output:
            return ""

        # Keep Windows' useful error description while avoiding excessively
        # verbose command output.
        lines = [
            line.strip()
            for line in output.splitlines()
            if line.strip()
        ]

        return " ".join(lines[-3:])

    @staticmethod
    def _creation_flags() -> int:
        """
        Prevent net.exe/cmdkey.exe console windows from flashing when JCAP
        is running as a GUI application.
        """
        if not sys.platform.startswith("win"):
            return 0

        return int(
            getattr(
                subprocess,
                "CREATE_NO_WINDOW",
                0,
            )
        )